Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CarritoFinal.Models;
using CarritoFinal.Service;


namespace CarritoFinal.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ICategoria _categoria;
        public CategoriaController(ICategoria categoria)
        {
            _categoria = categoria;
        }
        //public IActionResult Index()
        //{
        //    return View(_categoria.GetAllCategorias());
        //}
        public IActionResult Index(DateTime? fechaInicio, DateTime? fechaFin)
        {
            var categorias = _categoria.GetAllCategorias();

            if (fechaInicio.HasValue && fechaFin.HasValue)
            {
                categorias = categorias.Where(c => c.FechaRegistro >= fechaInicio && c.FechaRegistro <= fechaFin);
            }

            return View(categorias);
        }
        [Route("Categoria/Eliminar/{codigo}")]
        public IActionResult eliminar(string codigo)
        {
            _categoria.remove(codigo);
            return RedirectToAction("Index");
        }
        public IActionResult Nuevo()
        {
            return View();
        }
        public IActionResult Grabar(Categoria obj)
        {
            _categoria.add(obj);
            return RedirectToAction("Index");
        }
        [Route("Categoria/Editar/{codigo}")]
        public IActionResult Editar(string codigo)
        {
            return View(_categoria.edit(codigo));
        }
        public IActionResult editarCategoria(Categoria obj)
        {
            _categoria.editDetails(obj);
            return RedirectToAction("Index");
        }
    }
}

Controllers/MarcaController.cs
using Microsoft.AspNetCore.Mvc;
using CarritoFinal.Models;
using CarritoFinal.Service;

namespace CarritoFinal.Controllers
{
    public class MarcaController : Controller
    {
        private readonly IMarca _marca;
        public MarcaController(IMarca marca)
        {
            _marca = marca;
        }
        public IActionResult Index()
        {
            return View(_marca.GetAllMarcas());
        }
        [Route("Marca/Eliminar/{codigo}")]
        public IActionResult eliminar(string codigo)
        {
            _marca.remove(codigo);
            return RedirectToAction("Index");
        }
        public IActionResult Nuevo()
        {
            return View();
        }
        public IActionResult Grabar(Marca obj)
        {
            _marca.add(obj);
            return RedirectToAction("Index");
        }
        [Route("Marca/Editar/{codigo}")]
        public IActionResult Editar(string codigo)
        {
            return View(_marca.edit(codigo));
        }
        public IActionResult editarMarca(Marca obj)
        {
            _marca.editDetails(obj);
            return RedirectToAction("Index");
        }
    }
}

Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using CarritoFinal.Models;
using CarritoFinal.Service;


namespace CarritoFinal.Controllers
{
    public class ProductoController : Controller
    {
        private readonly IProducto _producto;
        public ProductoController(IProducto producto)
        {
            _producto = producto;
        }
        public IActionResult Index()
        {
            return View(_producto.GetAllProductos());
        }
        [Route("Producto/Eliminar/{codigo}")]
        public IActionResult eliminar(string codigo)
        {
            _producto.remove(codigo);
            return RedirectToAction("Index");
        }
        public IActionResult Nuevo()
        {
            return View();
        }
        public IActionResult Grabar(Producto obj)
        {
            _producto.add(obj);
            return RedirectToAction("Index");
        }
        [Route("Producto/Editar/{codigo}")]
        public IActionResult Editar(string codigo)
        {
            return View(_producto.edit(codigo));
        }
        public IActionResult editarProducto(Producto obj)
        {
            _producto.editDetails(obj);
            return RedirectToAction("Index");
        }
    }
}

Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CarritoFinal.Models;
using CarritoFinal.Service;

namespace CarritoFinal.Controllers
{
	public class UsuarioController : Controller
	{
		private readonly IUsuario _usuario;
		public UsuarioController(IUsuario usuario)
		{
			_usuario = usuario;
		}
		public IActionResult Index()
		{
			return View(_usuario.GetAllUsuarios());
		}
		[Route("Usuario/Eliminar/{codigo}")]
		public IActionResult eliminar(string codigo)
		{
			_usuario.remove(codigo);
			return RedirectToAction("Index");
		}
		public IActionResult Nuevo()
		{
			return View();
		}
		public IActionResult Grabar(Usuario obj)
		{
			_usuario.add(obj);
			return RedirectToAction("Index");
		}
		[Route("Usuario/Editar/{codigo}")]
		public IActionResult Editar(string codigo)
		{
			return View(_usuario.edit(codigo));
		}
		public IActionResult editarUsuario(Usuario obj)
		{
			_usuario.editDetails(obj);
			return RedirectToAction("Index");
		}
	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarritoFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarritoFinal.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/9adb84f91b.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Finiro</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <!--<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>-->
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Correo del Usuario</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Cerrar Sesion</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" asp-area="" asp-controller="Dashboard" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Usuarios
                        </a>
                        <div class="sb-sidenav-menu-heading">Mantenimiento</div>
                        <a class="nav-link" asp-area="" asp-controller="Categoria" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Categorias
                        </a>
                        <a class="nav-link" asp-area="" asp-controller="Marca" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-bookmark"></i></div>
                            Marcas
                        </a>
                        <a class="nav-link" asp-area="" asp-controller="Producto" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-boxes"></i></div>
                            Productos
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>